package Model;
// Generated 2016-01-09 13:04:29 by Hibernate Tools 4.3.1



/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer id;
     private String login;
     private String password;
     private String type;
     private String confirmed;
     private String address;

    public User() {
    }

    public User(String login, String password, String type, String confirmed, String address) {
       this.login = login;
       this.password = password;
       this.type = type;
       this.confirmed = confirmed;
       this.address = address;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getConfirmed() {
        return this.confirmed;
    }
    
    public void setConfirmed(String confirmed) {
        this.confirmed = confirmed;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }




}


